TestData:
    Headers: {"Content-Type": "application/json"}
    Jenkins_Host: 'http://bot-testing-framework.aineva.com/api/jenkins/run-conversation/{0}'
    api_conversation: 'http://bot-testing-framework.aineva.com/api/conversations'
    api_environment: 'http://bot-testing-framework.aineva.com/api/environments'
    Slack_token: ''
    Slack_recipient: "#api-testing"
